import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './Providers'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextAuth-App | SURAJ',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  )
}
